# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/chat.proto',
  package='chat',
  syntax='proto3',
  serialized_pb=_b('\n\x11protos/chat.proto\x12\x04\x63hat\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\x0cLoginRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x10\n\x0eLogoutResponse\" \n\rStreamRequest\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x89\x03\n\x0eStreamResponse\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0c\x63lient_login\x18\x02 \x01(\x0b\x32\x1a.chat.StreamResponse.LoginH\x00\x12\x34\n\rclient_logout\x18\x03 \x01(\x0b\x32\x1b.chat.StreamResponse.LogoutH\x00\x12\x36\n\x0e\x63lient_message\x18\x04 \x01(\x0b\x32\x1c.chat.StreamResponse.MessageH\x00\x12\x38\n\x0fserver_shutdown\x18\x05 \x01(\x0b\x32\x1d.chat.StreamResponse.ShutdownH\x00\x1a\x15\n\x05Login\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x16\n\x06Logout\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a(\n\x07Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a\n\n\x08ShutdownB\x07\n\x05\x65vent2\xac\x01\n\x04\x43hat\x12\x32\n\x05Login\x12\x12.chat.LoginRequest\x1a\x13.chat.LoginResponse\"\x00\x12\x35\n\x06Logout\x12\x13.chat.LogoutRequest\x1a\x14.chat.LogoutResponse\"\x00\x12\x39\n\x06Stream\x12\x13.chat.StreamRequest\x1a\x14.chat.StreamResponse\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='chat.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='chat.LoginRequest.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.LoginRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=106,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='chat.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='chat.LoginResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=138,
)


_LOGOUTREQUEST = _descriptor.Descriptor(
  name='LogoutRequest',
  full_name='chat.LogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='chat.LogoutRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=170,
)


_LOGOUTRESPONSE = _descriptor.Descriptor(
  name='LogoutResponse',
  full_name='chat.LogoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=188,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='chat.StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='chat.StreamRequest.message', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=222,
)


_STREAMRESPONSE_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='chat.StreamResponse.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.StreamResponse.Login.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=531,
)

_STREAMRESPONSE_LOGOUT = _descriptor.Descriptor(
  name='Logout',
  full_name='chat.StreamResponse.Logout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.StreamResponse.Logout.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=555,
)

_STREAMRESPONSE_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='chat.StreamResponse.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.StreamResponse.Message.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='chat.StreamResponse.Message.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=597,
)

_STREAMRESPONSE_SHUTDOWN = _descriptor.Descriptor(
  name='Shutdown',
  full_name='chat.StreamResponse.Shutdown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=609,
)

_STREAMRESPONSE = _descriptor.Descriptor(
  name='StreamResponse',
  full_name='chat.StreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='chat.StreamResponse.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_login', full_name='chat.StreamResponse.client_login', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_logout', full_name='chat.StreamResponse.client_logout', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_message', full_name='chat.StreamResponse.client_message', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_shutdown', full_name='chat.StreamResponse.server_shutdown', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STREAMRESPONSE_LOGIN, _STREAMRESPONSE_LOGOUT, _STREAMRESPONSE_MESSAGE, _STREAMRESPONSE_SHUTDOWN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='chat.StreamResponse.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=225,
  serialized_end=618,
)

_STREAMRESPONSE_LOGIN.containing_type = _STREAMRESPONSE
_STREAMRESPONSE_LOGOUT.containing_type = _STREAMRESPONSE
_STREAMRESPONSE_MESSAGE.containing_type = _STREAMRESPONSE
_STREAMRESPONSE_SHUTDOWN.containing_type = _STREAMRESPONSE
_STREAMRESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STREAMRESPONSE.fields_by_name['client_login'].message_type = _STREAMRESPONSE_LOGIN
_STREAMRESPONSE.fields_by_name['client_logout'].message_type = _STREAMRESPONSE_LOGOUT
_STREAMRESPONSE.fields_by_name['client_message'].message_type = _STREAMRESPONSE_MESSAGE
_STREAMRESPONSE.fields_by_name['server_shutdown'].message_type = _STREAMRESPONSE_SHUTDOWN
_STREAMRESPONSE.oneofs_by_name['event'].fields.append(
  _STREAMRESPONSE.fields_by_name['client_login'])
_STREAMRESPONSE.fields_by_name['client_login'].containing_oneof = _STREAMRESPONSE.oneofs_by_name['event']
_STREAMRESPONSE.oneofs_by_name['event'].fields.append(
  _STREAMRESPONSE.fields_by_name['client_logout'])
_STREAMRESPONSE.fields_by_name['client_logout'].containing_oneof = _STREAMRESPONSE.oneofs_by_name['event']
_STREAMRESPONSE.oneofs_by_name['event'].fields.append(
  _STREAMRESPONSE.fields_by_name['client_message'])
_STREAMRESPONSE.fields_by_name['client_message'].containing_oneof = _STREAMRESPONSE.oneofs_by_name['event']
_STREAMRESPONSE.oneofs_by_name['event'].fields.append(
  _STREAMRESPONSE.fields_by_name['server_shutdown'])
_STREAMRESPONSE.fields_by_name['server_shutdown'].containing_oneof = _STREAMRESPONSE.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['LogoutRequest'] = _LOGOUTREQUEST
DESCRIPTOR.message_types_by_name['LogoutResponse'] = _LOGOUTRESPONSE
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
DESCRIPTOR.message_types_by_name['StreamResponse'] = _STREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTREQUEST,
  __module__ = 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LogoutRequest)
  ))
_sym_db.RegisterMessage(LogoutRequest)

LogoutResponse = _reflection.GeneratedProtocolMessageType('LogoutResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTRESPONSE,
  __module__ = 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LogoutResponse)
  ))
_sym_db.RegisterMessage(LogoutResponse)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMREQUEST,
  __module__ = 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.StreamRequest)
  ))
_sym_db.RegisterMessage(StreamRequest)

StreamResponse = _reflection.GeneratedProtocolMessageType('StreamResponse', (_message.Message,), dict(

  Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), dict(
    DESCRIPTOR = _STREAMRESPONSE_LOGIN,
    __module__ = 'protos.chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Login)
    ))
  ,

  Logout = _reflection.GeneratedProtocolMessageType('Logout', (_message.Message,), dict(
    DESCRIPTOR = _STREAMRESPONSE_LOGOUT,
    __module__ = 'protos.chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Logout)
    ))
  ,

  Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
    DESCRIPTOR = _STREAMRESPONSE_MESSAGE,
    __module__ = 'protos.chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Message)
    ))
  ,

  Shutdown = _reflection.GeneratedProtocolMessageType('Shutdown', (_message.Message,), dict(
    DESCRIPTOR = _STREAMRESPONSE_SHUTDOWN,
    __module__ = 'protos.chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Shutdown)
    ))
  ,
  DESCRIPTOR = _STREAMRESPONSE,
  __module__ = 'protos.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.StreamResponse)
  ))
_sym_db.RegisterMessage(StreamResponse)
_sym_db.RegisterMessage(StreamResponse.Login)
_sym_db.RegisterMessage(StreamResponse.Logout)
_sym_db.RegisterMessage(StreamResponse.Message)
_sym_db.RegisterMessage(StreamResponse.Shutdown)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='chat.Chat',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=621,
  serialized_end=793,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='chat.Chat.Login',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Logout',
    full_name='chat.Chat.Logout',
    index=1,
    containing_service=None,
    input_type=_LOGOUTREQUEST,
    output_type=_LOGOUTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stream',
    full_name='chat.Chat.Stream',
    index=2,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_STREAMRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
